const std = @import("std");
const font_vector = @import("font_vector.zig");
const bytes = @import("bytes.zig");

pub const atlas_width: usize = 1024;
pub const atlas_height: usize = 1024;
pub const atlas_bytes: usize = atlas_width * atlas_height;
pub const replacement_codepoint: u21 = std.unicode.replacement_character;

pub const Weight = enum(u8) {
    regular,
    semibold,
    bold,
};

/// Canonical EdgeRun objects generated by gen-font tool.
/// Body starts at byte 148 (object.header_size) for bytes-kind objects with no owners/envelopes/children.
const regular_obj = @embedFile("assets/font_regular.obj");
const semibold_obj = @embedFile("assets/font_semibold.obj");
const bold_obj = @embedFile("assets/font_bold.obj");

const object_body_offset = 148;

fn readCount(comptime obj: []const u8, comptime offset: usize) usize {
    const raw = obj[object_body_offset..];
    return @intCast((bytes.load32(raw[offset..][0..4]) orelse @compileError("bad font body")));
}

pub const regular_counts = .{
    .glyphs = readCount(regular_obj, 12),
    .commands = readCount(regular_obj, 16),
    .kerns = readCount(regular_obj, 20),
};
pub const semibold_counts = .{
    .glyphs = readCount(semibold_obj, 12),
    .commands = readCount(semibold_obj, 16),
    .kerns = readCount(semibold_obj, 20),
};
pub const bold_counts = .{
    .glyphs = readCount(bold_obj, 12),
    .commands = readCount(bold_obj, 16),
    .kerns = readCount(bold_obj, 20),
};

pub const codepoint_count: usize = regular_counts.glyphs;

const max_glyphs = blk: {
    break :blk @max(@max(regular_counts.glyphs, semibold_counts.glyphs), bold_counts.glyphs);
};
const max_kerns = blk: {
    break :blk @max(@max(regular_counts.kerns, semibold_counts.kerns), bold_counts.kerns);
};
const max_commands = blk: {
    break :blk @max(@max(regular_counts.commands, semibold_counts.commands), bold_counts.commands);
};

const Storage = struct {
    metrics: font_vector.Metrics,
    glyphs: [max_glyphs]font_vector.GlyphRecord,
    kerns: [max_kerns]font_vector.KernRecord,
    commands: [max_commands]font_vector.Command,
    glyph_count: usize,
    kern_count: usize,
    command_count: usize,
    decoded: bool,
};

var regular_storage: Storage = .{
    .glyphs = undefined,
    .kerns = undefined,
    .commands = undefined,
    .glyph_count = 0,
    .kern_count = 0,
    .command_count = 0,
    .decoded = false,
    .metrics = undefined,
};
var semibold_storage: Storage = .{
    .glyphs = undefined,
    .kerns = undefined,
    .commands = undefined,
    .glyph_count = 0,
    .kern_count = 0,
    .command_count = 0,
    .decoded = false,
    .metrics = undefined,
};
var bold_storage: Storage = .{
    .glyphs = undefined,
    .kerns = undefined,
    .commands = undefined,
    .glyph_count = 0,
    .kern_count = 0,
    .command_count = 0,
    .decoded = false,
    .metrics = undefined,
};

fn ensureWeight(weight: Weight) void {
    const storage = switch (weight) {
        .regular => &regular_storage,
        .semibold => &semibold_storage,
        .bold => &bold_storage,
    };
    if (!storage.decoded) {
        const obj = switch (weight) {
            .regular => regular_obj,
            .semibold => semibold_obj,
            .bold => bold_obj,
        };
        const raw = obj[object_body_offset..];
        const decoded = font_vector.decodeBody(raw, &storage.glyphs, &storage.kerns, &storage.commands) orelse unreachable;
        storage.metrics = decoded.metrics;
        storage.glyph_count = decoded.glyphs.len;
        storage.kern_count = decoded.kerns.len;
        storage.command_count = decoded.commands.len;
        storage.decoded = true;
    }
}

pub fn body(weight: Weight) font_vector.Body {
    ensureWeight(weight);
    const storage = switch (weight) {
        .regular => &regular_storage,
        .semibold => &semibold_storage,
        .bold => &bold_storage,
    };
    return .{
        .metrics = storage.metrics,
        .glyphs = storage.glyphs[0..storage.glyph_count],
        .kerns = storage.kerns[0..storage.kern_count],
        .commands = storage.commands[0..storage.command_count],
    };
}

pub fn weightValue(weight: Weight) f32 {
    return switch (weight) {
        .regular => 400.0,
        .semibold => 600.0,
        .bold => 700.0,
    };
}
