#include "app_scaffold.h"

const char ERB_UI_APP_SCAFFOLD_MANIFEST[] =
    "contract=ui-app\n"
    "memory_pages=1\n"
    "imports=edgerun.ui/emit\n"
    "source=app.erc\n"
    "output=.build/app.wasm\n";

const char ERB_BUS_DRIVER_SCAFFOLD_MANIFEST[] =
    "contract=bus-driver\n"
    "memory_pages=1\n"
    "imports=edgerun.bus/exec\n"
    "driver_memory_bytes=65536\n"
    "driver_bus=mmio32:4096:4:read8\n"
    "source=app.erc\n"
    "output=.build/app.wasm\n";

const char ERB_UI_APP_SCAFFOLD_SOURCE[] =
    "extern i64 ui_emit(i64, i64) __import(\"edgerun.ui\", \"emit\");\n"
    "const i64 APP_OUTBOX = 1024;\n"
    "const i64 APP_PACKET_BYTES = 172;\n"
    "const i64 APP_PACKET_BYTES_SLOT = 172;\n"
    "const i64 UI_ABI_VERSION = 1;\n"
    "const i64 UI_COMMAND_COUNT = 3;\n"
    "const i64 UI_RECT_COUNT = 1;\n"
    "const i64 UI_HIT_COUNT = 1;\n"
    "const i64 UI_EMPTY_COUNT = 0;\n"
    "const i64 UI_TEXT_COUNT = 1;\n"
    "const i64 UI_HIT_KIND_BUTTON = 3;\n"
    "const i64 UI_HIT_ID = 7;\n"
    "const i64 UI_TEXT_ATLAS_ID = 2;\n"
    "const i64 UI_HEADER_ABI = 0;\n"
    "const i64 UI_HEADER_COMMANDS = 4;\n"
    "const i64 UI_HEADER_RECTS = 8;\n"
    "const i64 UI_HEADER_HITS = 12;\n"
    "const i64 UI_HEADER_DRAG_SOURCES = 16;\n"
    "const i64 UI_HEADER_DROP_TARGETS = 20;\n"
    "const i64 UI_HEADER_TRANSITIONS = 24;\n"
    "const i64 UI_HEADER_ICON_QUADS = 28;\n"
    "const i64 UI_HEADER_TEXT_QUADS = 32;\n"
    "const i64 UI_RECT_X = 36;\n"
    "const i64 UI_RECT_Y = 40;\n"
    "const i64 UI_RECT_W = 44;\n"
    "const i64 UI_RECT_H = 48;\n"
    "const i64 UI_RECT_RADIUS = 52;\n"
    "const i64 UI_RECT_COLOR_R = 56;\n"
    "const i64 UI_RECT_COLOR_G = 60;\n"
    "const i64 UI_RECT_COLOR_B = 64;\n"
    "const i64 UI_RECT_COLOR_A = 68;\n"
    "const i64 UI_RECT_COLOR2_R = 72;\n"
    "const i64 UI_RECT_COLOR2_G = 76;\n"
    "const i64 UI_RECT_COLOR2_B = 80;\n"
    "const i64 UI_RECT_COLOR2_A = 84;\n"
    "const i64 UI_RECT_MODE = 88;\n"
    "const i64 UI_RECT_SHADOW = 92;\n"
    "const i64 UI_HIT_KIND = 96;\n"
    "const i64 UI_HIT_RECORD_ID = 100;\n"
    "const i64 UI_HIT_X = 104;\n"
    "const i64 UI_HIT_Y = 108;\n"
    "const i64 UI_HIT_W = 112;\n"
    "const i64 UI_HIT_H = 116;\n"
    "const i64 UI_TEXT_X = 120;\n"
    "const i64 UI_TEXT_Y = 124;\n"
    "const i64 UI_TEXT_W = 128;\n"
    "const i64 UI_TEXT_H = 132;\n"
    "const i64 UI_TEXT_U0 = 136;\n"
    "const i64 UI_TEXT_V0 = 140;\n"
    "const i64 UI_TEXT_U1 = 144;\n"
    "const i64 UI_TEXT_V1 = 148;\n"
    "const i64 UI_TEXT_ATLAS = 152;\n"
    "const i64 UI_TEXT_COLOR_R = 156;\n"
    "const i64 UI_TEXT_COLOR_G = 160;\n"
    "const i64 UI_TEXT_COLOR_B = 164;\n"
    "const i64 UI_TEXT_COLOR_A = 168;\n"
    "const i64 F32_RECT_X = 0x41200000;\n"
    "const i64 F32_RECT_Y = 0x41a00000;\n"
    "const i64 F32_RECT_W = 0x42f00000;\n"
    "const i64 F32_RECT_H = 0x42480000;\n"
    "const i64 F32_RECT_RADIUS = 0x41000000;\n"
    "const i64 F32_PANEL_R = 0x3e800000;\n"
    "const i64 F32_PANEL_G = 0x3f000000;\n"
    "const i64 F32_PANEL_B = 0x3f400000;\n"
    "const i64 F32_ONE = 0x3f800000;\n"
    "const i64 F32_TEXT_X = 0x41300000;\n"
    "const i64 F32_TEXT_Y = 0x41b00000;\n"
    "const i64 F32_TEXT_SIZE = 0x41800000;\n"
    "const i64 UI_RECT_MODE_FILL = 0;\n"
    "memory(1);\n"
    "export i64 main(void) {\n"
    "  i64 ptr = APP_OUTBOX;\n"
    "  i64 len = 0;\n"
    "  store32(ptr, APP_PACKET_BYTES_SLOT, APP_PACKET_BYTES);\n"
    "  len = load32(ptr, APP_PACKET_BYTES_SLOT);\n"
    "  store16(ptr, UI_HEADER_ABI, UI_ABI_VERSION);\n"
    "  store32(ptr, UI_HEADER_COMMANDS, UI_COMMAND_COUNT);\n"
    "  store32(ptr, UI_HEADER_RECTS, UI_RECT_COUNT);\n"
    "  store32(ptr, UI_HEADER_HITS, UI_HIT_COUNT);\n"
    "  store32(ptr, UI_HEADER_DRAG_SOURCES, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_HEADER_DROP_TARGETS, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_HEADER_TRANSITIONS, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_HEADER_ICON_QUADS, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_HEADER_TEXT_QUADS, UI_TEXT_COUNT);\n"
    "  store32(ptr, UI_RECT_X, F32_RECT_X);\n"
    "  store32(ptr, UI_RECT_Y, F32_RECT_Y);\n"
    "  store32(ptr, UI_RECT_W, F32_RECT_W);\n"
    "  store32(ptr, UI_RECT_H, F32_RECT_H);\n"
    "  store32(ptr, UI_RECT_RADIUS, F32_RECT_RADIUS);\n"
    "  store32(ptr, UI_RECT_COLOR_R, F32_PANEL_R);\n"
    "  store32(ptr, UI_RECT_COLOR_G, F32_PANEL_G);\n"
    "  store32(ptr, UI_RECT_COLOR_B, F32_PANEL_B);\n"
    "  store32(ptr, UI_RECT_COLOR_A, F32_ONE);\n"
    "  store32(ptr, UI_RECT_COLOR2_R, F32_PANEL_R);\n"
    "  store32(ptr, UI_RECT_COLOR2_G, F32_PANEL_G);\n"
    "  store32(ptr, UI_RECT_COLOR2_B, F32_PANEL_B);\n"
    "  store32(ptr, UI_RECT_COLOR2_A, F32_ONE);\n"
    "  store32(ptr, UI_RECT_MODE, UI_RECT_MODE_FILL);\n"
    "  store32(ptr, UI_RECT_SHADOW, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_HIT_KIND, UI_HIT_KIND_BUTTON);\n"
    "  store32(ptr, UI_HIT_RECORD_ID, UI_HIT_ID);\n"
    "  store32(ptr, UI_HIT_X, F32_RECT_X);\n"
    "  store32(ptr, UI_HIT_Y, F32_RECT_Y);\n"
    "  store32(ptr, UI_HIT_W, F32_RECT_W);\n"
    "  store32(ptr, UI_HIT_H, F32_RECT_H);\n"
    "  store32(ptr, UI_TEXT_X, F32_TEXT_X);\n"
    "  store32(ptr, UI_TEXT_Y, F32_TEXT_Y);\n"
    "  store32(ptr, UI_TEXT_W, F32_TEXT_SIZE);\n"
    "  store32(ptr, UI_TEXT_H, F32_TEXT_SIZE);\n"
    "  store32(ptr, UI_TEXT_U0, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_TEXT_V0, UI_EMPTY_COUNT);\n"
    "  store32(ptr, UI_TEXT_U1, F32_ONE);\n"
    "  store32(ptr, UI_TEXT_V1, F32_ONE);\n"
    "  store32(ptr, UI_TEXT_ATLAS, UI_TEXT_ATLAS_ID);\n"
    "  store32(ptr, UI_TEXT_COLOR_R, F32_ONE);\n"
    "  store32(ptr, UI_TEXT_COLOR_G, F32_ONE);\n"
    "  store32(ptr, UI_TEXT_COLOR_B, F32_ONE);\n"
    "  store32(ptr, UI_TEXT_COLOR_A, F32_ONE);\n"
    "  return ui_emit(ptr, len);\n"
    "}\n";

const char ERB_BUS_DRIVER_SCAFFOLD_SOURCE[] =
    "extern i64 bus_exec(i64, i64) __import(\"edgerun.bus\", \"exec\");\n"
    "\n"
    "const i64 DRIVER_REQUEST = 0;\n"
    "const i64 DRIVER_RESPONSE = 128;\n"
    "const i64 DRIVER_ABI_VERSION = 1;\n"
    "const i64 DRIVER_PACKET_IO_REQUEST = 3;\n"
    "const i64 DRIVER_BUS_KIND_MMIO32 = 2;\n"
    "const i64 DRIVER_BUS_ACCESS_READ8 = 4;\n"
    "const i64 DRIVER_WIDTH8 = 1;\n"
    "const i64 DRIVER_PACKET_ID = 1;\n"
    "const i64 DRIVER_MMIO_BASE = 4096;\n"
    "const i64 DRIVER_MMIO_LEN = 4;\n"
    "\n"
    "const i64 BUS_PACKET_ABI = 0;\n"
    "const i64 BUS_PACKET_KIND = 2;\n"
    "const i64 BUS_PACKET_ID = 8;\n"
    "const i64 BUS_PACKET_OP_ABI = 16;\n"
    "const i64 BUS_PACKET_OP_KIND = 18;\n"
    "const i64 BUS_PACKET_OP_ACCESS = 20;\n"
    "const i64 BUS_PACKET_OP_WIDTH = 24;\n"
    "const i64 BUS_PACKET_ADDRESS_ABI = 32;\n"
    "const i64 BUS_PACKET_ADDRESS_KIND = 34;\n"
    "const i64 BUS_PACKET_ADDRESS_ACCESS = 36;\n"
    "const i64 BUS_PACKET_ADDRESS_BASE = 64;\n"
    "const i64 BUS_PACKET_ADDRESS_LEN = 72;\n"
    "const i64 BUS_PACKET_RESPONSE_RESULT = 96;\n"
    "\n"
    "memory(1);\n"
    "\n"
    "export i64 main(void) {\n"
    "  i64 request = DRIVER_REQUEST;\n"
    "  i64 response = DRIVER_RESPONSE;\n"
    "  i64 ok = 0;\n"
    "  store16(request, BUS_PACKET_ABI, DRIVER_ABI_VERSION);\n"
    "  store16(request, BUS_PACKET_KIND, DRIVER_PACKET_IO_REQUEST);\n"
    "  store64(request, BUS_PACKET_ID, DRIVER_PACKET_ID);\n"
    "  store16(request, BUS_PACKET_OP_ABI, DRIVER_ABI_VERSION);\n"
    "  store16(request, BUS_PACKET_OP_KIND, DRIVER_BUS_KIND_MMIO32);\n"
    "  store32(request, BUS_PACKET_OP_ACCESS, DRIVER_BUS_ACCESS_READ8);\n"
    "  store32(request, BUS_PACKET_OP_WIDTH, DRIVER_WIDTH8);\n"
    "  store16(request, BUS_PACKET_ADDRESS_ABI, DRIVER_ABI_VERSION);\n"
    "  store16(request, BUS_PACKET_ADDRESS_KIND, DRIVER_BUS_KIND_MMIO32);\n"
    "  store32(request, BUS_PACKET_ADDRESS_ACCESS, DRIVER_BUS_ACCESS_READ8);\n"
    "  store64(request, BUS_PACKET_ADDRESS_BASE, DRIVER_MMIO_BASE);\n"
    "  store64(request, BUS_PACKET_ADDRESS_LEN, DRIVER_MMIO_LEN);\n"
    "  ok = bus_exec(request, response);\n"
    "  return load64(response, BUS_PACKET_RESPONSE_RESULT);\n"
    "}\n";
