const std = @import("std");

pub const GLenum = i32;
pub const GLint = i32;
pub const GLuint = u32;
pub const GLsizei = i32;
pub const GLboolean = i32;
pub const GLbitfield = u32;
pub const GLfloat = f32;
pub const GLsizeiptr = i32;
pub const GLintptr = i32;

pub const gl_vertex_shader: GLenum = 0x8B31;
pub const gl_fragment_shader: GLenum = 0x8B30;
pub const gl_compile_status: GLenum = 0x8B81;
pub const gl_link_status: GLenum = 0x8B82;
pub const gl_dither: GLenum = 0x0BD0;
pub const gl_blend: GLenum = 0x0BE2;
pub const gl_one: GLenum = 1;
pub const gl_one_minus_src_alpha: GLenum = 0x0303;
pub const gl_color_buffer_bit: GLbitfield = 0x00004000;
pub const gl_array_buffer: GLenum = 0x8892;
pub const gl_static_draw: GLenum = 0x88E4;
pub const gl_dynamic_draw: GLenum = 0x88E8;
pub const gl_float: GLenum = 0x1406;
pub const gl_false: GLboolean = 0;
pub const gl_triangle_strip: GLenum = 0x0005;
pub const gl_triangles: GLenum = 0x0004;
pub const gl_texture_2d: GLenum = 0x0DE1;
pub const gl_texture0: GLenum = 0x84C0;
pub const gl_texture_min_filter: GLenum = 0x2801;
pub const gl_texture_mag_filter: GLenum = 0x2800;
pub const gl_texture_wrap_s: GLenum = 0x2802;
pub const gl_texture_wrap_t: GLenum = 0x2803;
pub const gl_clamp_to_edge: GLenum = 0x812F;
pub const gl_alpha: GLenum = 0x1906;
pub const gl_rgba: GLenum = 0x1908;
pub const gl_unsigned_byte: GLenum = 0x1401;
pub const gl_luminance: GLenum = 0x1909;
pub const gl_linear: GLenum = 0x2601;
pub const gl_nearest: GLenum = 0x2600;
pub const gl_unpack_alignment: GLenum = 0x0CF5;

pub extern fn glActiveTexture(texture: GLenum) void;
pub extern fn glAttachShader(program: GLuint, shader: GLuint) void;
pub extern fn glBindAttribLocation(program: GLuint, index: GLuint, ptr: GLuint, len: GLuint) void;
pub extern fn glBindBuffer(target: GLenum, buffer: GLuint) void;
pub extern fn glBindTexture(target: GLenum, texture: GLuint) void;
pub extern fn glBlendFuncSeparate(src_rgb: GLenum, dst_rgb: GLenum, src_a: GLenum, dst_a: GLenum) void;
pub extern fn glBufferData(target: GLenum, size: GLsizeiptr, ptr: GLuint, usage: GLenum) void;
pub extern fn glClear(mask: GLbitfield) void;
pub extern fn glClearColor(r: GLfloat, g: GLfloat, b: GLfloat, a: GLfloat) void;
pub extern fn glCompileShader(shader: GLuint) void;
pub extern fn glCreateProgram() GLuint;
pub extern fn glCreateShader(kind: GLenum) GLuint;
pub extern fn glDeleteBuffers(n: GLsizei, ptr: GLuint) void;
pub extern fn glDeleteProgram(program: GLuint) void;
pub extern fn glDeleteShader(shader: GLuint) void;
pub extern fn glDeleteTextures(n: GLsizei, ptr: GLuint) void;
pub extern fn glDisable(cap: GLenum) void;
pub extern fn glDrawArrays(mode: GLenum, first: GLint, count: GLsizei) void;
pub extern fn glEnable(cap: GLenum) void;
pub extern fn glEnableVertexAttribArray(index: GLuint) void;
pub extern fn glGenBuffers(n: GLsizei) GLuint;
pub extern fn glGenTextures(n: GLsizei) GLuint;
pub extern fn glGetProgramiv(program: GLuint, pname: GLenum) GLint;
pub extern fn glGetShaderiv(shader: GLuint, pname: GLenum) GLint;
pub extern fn glGetUniformLocation(program: GLuint, ptr: GLuint, len: GLuint) GLint;
pub extern fn glLinkProgram(program: GLuint) void;
pub extern fn glPixelStorei(pname: GLenum, param: GLint) void;
pub extern fn glShaderSource(shader: GLuint, count: GLsizei, ptr: GLuint, len: GLuint) void;
pub extern fn glTexImage2D(target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type_: GLenum, ptr: GLuint) void;
pub extern fn glTexParameteri(target: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glTexSubImage2D(target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, ptr: GLuint) void;
pub extern fn glUniform1f(location: GLint, v0: GLfloat) void;
pub extern fn glUniform1i(location: GLint, v0: GLint) void;
pub extern fn glUniform2f(location: GLint, v0: GLfloat, v1: GLfloat) void;
pub extern fn glUniform4f(location: GLint, v0: GLfloat, v1: GLfloat, v2: GLfloat, v3: GLfloat) void;
pub extern fn glUseProgram(program: GLuint) void;
pub extern fn glVertexAttribPointer(index: GLuint, size: GLint, type_: GLenum, normalized: GLboolean, stride: GLsizei, ptr: GLuint) void;
pub extern fn glViewport(x: GLint, y: GLint, width: GLsizei, height: GLsizei) void;
