extern i64 bus_exec(i64, i64) __import("edgerun.bus", "exec");

const i64 DRIVER_REQUEST = 0;
const i64 DRIVER_RESPONSE = 128;
const i64 DRIVER_ABI_VERSION = 1;
const i64 DRIVER_PACKET_IO_REQUEST = 3;
const i64 DRIVER_BUS_KIND_MMIO32 = 2;
const i64 DRIVER_BUS_ACCESS_READ8 = 4;
const i64 DRIVER_WIDTH8 = 1;
const i64 DRIVER_PACKET_ID = 1;
const i64 DRIVER_MMIO_BASE = 4096;
const i64 DRIVER_MMIO_LEN = 4;

const i64 BUS_PACKET_ABI = 0;
const i64 BUS_PACKET_KIND = 2;
const i64 BUS_PACKET_ID = 8;
const i64 BUS_PACKET_OP_ABI = 16;
const i64 BUS_PACKET_OP_KIND = 18;
const i64 BUS_PACKET_OP_ACCESS = 20;
const i64 BUS_PACKET_OP_WIDTH = 24;
const i64 BUS_PACKET_ADDRESS_ABI = 32;
const i64 BUS_PACKET_ADDRESS_KIND = 34;
const i64 BUS_PACKET_ADDRESS_ACCESS = 36;
const i64 BUS_PACKET_ADDRESS_BASE = 64;
const i64 BUS_PACKET_ADDRESS_LEN = 72;
const i64 BUS_PACKET_RESPONSE_RESULT = 96;

memory(1);

export i64 main(void) {
  i64 request = DRIVER_REQUEST;
  i64 response = DRIVER_RESPONSE;
  i64 ok = 0;
  store16(request, BUS_PACKET_ABI, DRIVER_ABI_VERSION);
  store16(request, BUS_PACKET_KIND, DRIVER_PACKET_IO_REQUEST);
  store64(request, BUS_PACKET_ID, DRIVER_PACKET_ID);
  store16(request, BUS_PACKET_OP_ABI, DRIVER_ABI_VERSION);
  store16(request, BUS_PACKET_OP_KIND, DRIVER_BUS_KIND_MMIO32);
  store32(request, BUS_PACKET_OP_ACCESS, DRIVER_BUS_ACCESS_READ8);
  store32(request, BUS_PACKET_OP_WIDTH, DRIVER_WIDTH8);
  store16(request, BUS_PACKET_ADDRESS_ABI, DRIVER_ABI_VERSION);
  store16(request, BUS_PACKET_ADDRESS_KIND, DRIVER_BUS_KIND_MMIO32);
  store32(request, BUS_PACKET_ADDRESS_ACCESS, DRIVER_BUS_ACCESS_READ8);
  store64(request, BUS_PACKET_ADDRESS_BASE, DRIVER_MMIO_BASE);
  store64(request, BUS_PACKET_ADDRESS_LEN, DRIVER_MMIO_LEN);
  ok = bus_exec(request, response);
  return load64(response, BUS_PACKET_RESPONSE_RESULT);
}
