#ifndef ER_PI_ZERO_W_V1_1_UART_H
#define ER_PI_ZERO_W_V1_1_UART_H

/*
 * Purpose: define the Raspberry Pi Zero W v1.1 early mini UART boundary.
 * Intention: make the first ARMv6 hardware proof visible over serial without
 * pulling in firmware, libc, or host assumptions.
 */

#include "er_types.h"

#define ER_PI_ZERO_W_V1_1_UART_PERIPHERAL_BASE 0x20000000u
#define ER_PI_ZERO_W_V1_1_GPIO_BASE 0x20200000u
#define ER_PI_ZERO_W_V1_1_EMMC_BASE 0x20300000u
#define ER_PI_ZERO_W_V1_1_AUX_BASE 0x20215000u

#define ER_PI_ZERO_W_V1_1_GPIO_GPFSEL1 0x00000004u
#define ER_PI_ZERO_W_V1_1_GPIO_GPFSEL3 0x0000000cu
#define ER_PI_ZERO_W_V1_1_GPIO_GPFSEL4 0x00000010u
#define ER_PI_ZERO_W_V1_1_GPIO_GPSET1 0x00000020u
#define ER_PI_ZERO_W_V1_1_GPIO_GPCLR1 0x0000002cu
#define ER_PI_ZERO_W_V1_1_GPIO_GPPUD 0x00000094u
#define ER_PI_ZERO_W_V1_1_GPIO_GPPUDCLK0 0x00000098u
#define ER_PI_ZERO_W_V1_1_GPIO_GPPUDCLK1 0x0000009cu

#define ER_PI_ZERO_W_V1_1_AUX_ENABLES 0x00000004u
#define ER_PI_ZERO_W_V1_1_AUX_MU_IO 0x00000040u
#define ER_PI_ZERO_W_V1_1_AUX_MU_IER 0x00000044u
#define ER_PI_ZERO_W_V1_1_AUX_MU_IIR 0x00000048u
#define ER_PI_ZERO_W_V1_1_AUX_MU_LCR 0x0000004cu
#define ER_PI_ZERO_W_V1_1_AUX_MU_MCR 0x00000050u
#define ER_PI_ZERO_W_V1_1_AUX_MU_LSR 0x00000054u
#define ER_PI_ZERO_W_V1_1_AUX_MU_CNTL 0x00000060u
#define ER_PI_ZERO_W_V1_1_AUX_MU_BAUD 0x00000068u

#define ER_PI_ZERO_W_V1_1_EMMC_REG_ARG1 0x00000008u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_CMDTM 0x0000000cu
#define ER_PI_ZERO_W_V1_1_EMMC_REG_RESP0 0x00000010u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_BLKSIZECNT 0x00000004u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_DATA 0x00000020u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_STATUS 0x00000024u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_CONTROL1 0x0000002cu
#define ER_PI_ZERO_W_V1_1_EMMC_REG_INTERRUPT 0x00000030u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_IRPT_MASK 0x00000034u
#define ER_PI_ZERO_W_V1_1_EMMC_REG_IRPT_EN 0x00000038u

#define ER_PI_ZERO_W_V1_1_EMMC_INTERRUPT_CMD_DONE 0x00000001u
#define ER_PI_ZERO_W_V1_1_EMMC_INTERRUPT_DATA_DONE 0x00000002u
#define ER_PI_ZERO_W_V1_1_EMMC_INTERRUPT_READ_RDY 0x00000020u
#define ER_PI_ZERO_W_V1_1_EMMC_INTERRUPT_ALL 0xffffffffu
#define ER_PI_ZERO_W_V1_1_EMMC_INTERRUPT_ERROR_MASK 0xffff0000u
#define ER_PI_ZERO_W_V1_1_EMMC_STATUS_CMD_INHIBIT 0x00000001u
#define ER_PI_ZERO_W_V1_1_EMMC_STATUS_DATA_INHIBIT 0x00000002u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_INTLEN 0x00000001u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_STABLE 0x00000002u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_EN 0x00000004u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_GENSEL 0x00000020u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_FREQ8_SHIFT 8u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_FREQ8_MASK 0x000000ffu
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_FREQ_MS2_SHIFT 6u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_CLK_FREQ_MS2_MASK 0x00000300u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_DATA_TOUNIT_SHIFT 16u
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_DATA_TOUNIT_MAX 0x0000000eu
#define ER_PI_ZERO_W_V1_1_EMMC_CONTROL1_SRST_HC 0x01000000u
#define ER_PI_ZERO_W_V1_1_EMMC_IDENT_CLOCK_DIVISOR 626u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_RESPONSE_BITS 16u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_RESPONSE_NONE 0u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_RESPONSE_48 2u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_BLOCK_COUNT_ENABLE 0x00000002u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_DATA_READ 0x00000010u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_CRC_CHECK 0x00080000u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_INDEX_CHECK 0x00100000u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_IS_DATA 0x00200000u
#define ER_PI_ZERO_W_V1_1_EMMC_CMDTM_INDEX_BITS 24u
#define ER_PI_ZERO_W_V1_1_EMMC_BLOCK_COUNT_BITS 16u

#define ER_PI_ZERO_W_V1_1_MMC_CMD_GO_IDLE_STATE 0u
#define ER_PI_ZERO_W_V1_1_MMC_CMD_SEND_RELATIVE_ADDR 3u
#define ER_PI_ZERO_W_V1_1_MMC_CMD_IO_SEND_OP_COND 5u
#define ER_PI_ZERO_W_V1_1_MMC_CMD_SELECT_CARD 7u
#define ER_PI_ZERO_W_V1_1_MMC_CMD_IO_RW_DIRECT 52u
#define ER_PI_ZERO_W_V1_1_MMC_CMD_IO_RW_EXTENDED 53u
#define ER_PI_ZERO_W_V1_1_MMC_RESPONSE_NONE 0u
#define ER_PI_ZERO_W_V1_1_MMC_RESPONSE_R1 1u
#define ER_PI_ZERO_W_V1_1_MMC_RESPONSE_R4 4u
#define ER_PI_ZERO_W_V1_1_MMC_RESPONSE_R5 5u
#define ER_PI_ZERO_W_V1_1_MMC_RESPONSE_R6 6u
#define ER_PI_ZERO_W_V1_1_SDIO_CMD52_READ 0u
#define ER_PI_ZERO_W_V1_1_SDIO_CMD53_READ 0u
#define ER_PI_ZERO_W_V1_1_SDIO_CMD52_NO_RAW 0u
#define ER_PI_ZERO_W_V1_1_SDIO_FUNCTION_BACKPLANE 1u
#define ER_PI_ZERO_W_V1_1_SDIO_FUNCTION_BITS 28u
#define ER_PI_ZERO_W_V1_1_SDIO_RAW_FLAG_BIT 27u
#define ER_PI_ZERO_W_V1_1_SDIO_BLOCK_MODE_BIT 27u
#define ER_PI_ZERO_W_V1_1_SDIO_INCREMENTING_ADDRESS_BIT 26u
#define ER_PI_ZERO_W_V1_1_SDIO_RW_FLAG_BIT 31u
#define ER_PI_ZERO_W_V1_1_SDIO_ADDRESS_BITS 9u
#define ER_PI_ZERO_W_V1_1_SDIO_FUNCTION_MASK 0x07u
#define ER_PI_ZERO_W_V1_1_SDIO_ADDRESS_MASK 0x0001ffffu
#define ER_PI_ZERO_W_V1_1_SDIO_CMD52_DATA_MASK 0xffu
#define ER_PI_ZERO_W_V1_1_SDIO_CMD53_COUNT_MASK 0x000001ffu
#define ER_PI_ZERO_W_V1_1_SDIO_CMD53_FIXED_ADDRESS 0u
#define ER_PI_ZERO_W_V1_1_SDIO_CMD53_BYTE_MODE 0u
#define ER_PI_ZERO_W_V1_1_SDIO_OCR_3V3 0x00300000u
#define ER_PI_ZERO_W_V1_1_MMC_RCA_MASK 0xffffu
#define ER_PI_ZERO_W_V1_1_MMC_RCA_RESPONSE_SHIFT 16u

#define ER_PI_ZERO_W_V1_1_GPIO_PIN_UART_TX 14u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_UART_RX 15u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_CLK 34u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_CMD 35u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT0 36u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT1 37u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT2 38u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT3 39u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_REG_ON 41u
#define ER_PI_ZERO_W_V1_1_GPIO_PIN_ACT_LED 47u
#define ER_PI_ZERO_W_V1_1_GPIO_OUTPUT 1u
#define ER_PI_ZERO_W_V1_1_GPIO_ALT5 2u
#define ER_PI_ZERO_W_V1_1_GPIO_ALT3 7u
#define ER_PI_ZERO_W_V1_1_GPIO_FSEL_BITS_PER_PIN 3u
#define ER_PI_ZERO_W_V1_1_GPIO_FSEL_PIN_MOD 10u
#define ER_PI_ZERO_W_V1_1_GPIO_FSEL_MASK 7u

#define ER_PI_ZERO_W_V1_1_GPIO_PULL_DISABLE 0u
#define ER_PI_ZERO_W_V1_1_GPIO_PULL_CLOCK_UART ((1u << ER_PI_ZERO_W_V1_1_GPIO_PIN_UART_TX) | \
                                    (1u << ER_PI_ZERO_W_V1_1_GPIO_PIN_UART_RX))
#define ER_PI_ZERO_W_V1_1_GPIO_PULL_CLOCK_WIFI_SDIO \
  ((1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_CLK - 32u)) | \
   (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_CMD - 32u)) | \
   (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT0 - 32u)) | \
   (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT1 - 32u)) | \
   (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT2 - 32u)) | \
   (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_SDIO_DAT3 - 32u)))
#define ER_PI_ZERO_W_V1_1_GPIO_SET_WIFI_REG_ON (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_WIFI_REG_ON - 32u))
#define ER_PI_ZERO_W_V1_1_GPIO_SET_ACT_LED (1u << (ER_PI_ZERO_W_V1_1_GPIO_PIN_ACT_LED - 32u))

#define ER_PI_ZERO_W_V1_1_AUX_ENABLE_MINI_UART 1u
#define ER_PI_ZERO_W_V1_1_AUX_MU_DISABLE 0u
#define ER_PI_ZERO_W_V1_1_AUX_MU_ENABLE_TX_RX 3u
#define ER_PI_ZERO_W_V1_1_AUX_MU_DISABLE_INTERRUPTS 0u
#define ER_PI_ZERO_W_V1_1_AUX_MU_CLEAR_FIFOS 0xc6u
#define ER_PI_ZERO_W_V1_1_AUX_MU_EIGHT_BIT_MODE 3u
#define ER_PI_ZERO_W_V1_1_AUX_MU_RTS_HIGH 0u
#define ER_PI_ZERO_W_V1_1_AUX_MU_LSR_TX_EMPTY 0x20u
#define ER_PI_ZERO_W_V1_1_AUX_MU_BAUD_115200_CORE_250MHZ 270u

#define ER_PI_ZERO_W_V1_1_UART_GPIO_DELAY_TICKS 150u
#define ER_PI_ZERO_W_V1_1_UART_HEARTBEAT_DELAY_TICKS 4000000u

#define ER_PI_ZERO_W_V1_1_SERIAL_HEX_DIGITS_U32 8u
#define ER_PI_ZERO_W_V1_1_SERIAL_HEX_NIBBLE_MASK 0x0fu
#define ER_PI_ZERO_W_V1_1_SERIAL_HEX_NIBBLE_BITS 4u
#define ER_PI_ZERO_W_V1_1_SERIAL_HEX_DECIMAL_DIGITS 10u
#define ER_PI_ZERO_W_V1_1_L2_NODE_BYTES 32u
#define ER_PI_ZERO_W_V1_1_L2_MAC_BYTES 6u
#define ER_PI_ZERO_W_V1_1_L2_MAC_LOCAL_UNICAST 0x02u
#define ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT 5u
#define ER_PI_ZERO_W_V1_1_L2_MAC_NODE_OFFSET 1u
#define ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_E_OFFSET 0u
#define ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_R_OFFSET 1u
#define ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_DASH_OFFSET 2u
#define ER_PI_ZERO_W_V1_1_L2_SSID_HEX_OFFSET 3u
#define ER_PI_ZERO_W_V1_1_L2_SSID_NODE_BYTES 8u
#define ER_PI_ZERO_W_V1_1_L2_HEX_DIGITS_PER_BYTE 2u
#define ER_PI_ZERO_W_V1_1_L2_SSID_BYTES 19u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_FIXED_BYTES 10u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_BYTES 29u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_MAC_OFFSET 0u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_ETH_TYPE_OFFSET 6u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_CHANNEL_OFFSET 8u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_SSID_LEN_OFFSET 9u
#define ER_PI_ZERO_W_V1_1_L2_ADDRESS_SSID_OFFSET 10u
#define ER_PI_ZERO_W_V1_1_L2_ETH_TYPE_EDGERUN 0x88b5u
#define ER_PI_ZERO_W_V1_1_L2_ETH_TYPE_HIGH_SHIFT 8u
#define ER_PI_ZERO_W_V1_1_L2_BYTE_MASK 0xffu
#define ER_PI_ZERO_W_V1_1_L2_HEX_HIGH_NIBBLE_SHIFT 4u
#define ER_PI_ZERO_W_V1_1_L2_HEX_NIBBLE_MASK 0x0fu
#define ER_PI_ZERO_W_V1_1_L2_WIFI_CHANNEL 6u

static inline UINT8 er_pi_zero_w_v1_1_node_id_nonzero(
    const UINT8 node_id[ER_PI_ZERO_W_V1_1_L2_NODE_BYTES]) {
  UINT32 i;

  if (node_id == 0) {
    return 0u;
  }
  for (i = 0u; i < ER_PI_ZERO_W_V1_1_L2_NODE_BYTES; ++i) {
    if (node_id[i] != 0u) {
      return 1u;
    }
  }
  return 0u;
}

static inline UINT8 er_pi_zero_w_v1_1_l2_hex_digit(UINT8 value) {
  UINT8 digit = (UINT8)(value & ER_PI_ZERO_W_V1_1_L2_HEX_NIBBLE_MASK);

  if (digit < ER_PI_ZERO_W_V1_1_SERIAL_HEX_DECIMAL_DIGITS) {
    return (UINT8)('0' + digit);
  }
  return (UINT8)('a' + (digit - ER_PI_ZERO_W_V1_1_SERIAL_HEX_DECIMAL_DIGITS));
}

static inline UINT8 er_pi_zero_w_v1_1_l2_node_mac(
    const UINT8 node_id[ER_PI_ZERO_W_V1_1_L2_NODE_BYTES],
    UINT8 out_mac[ER_PI_ZERO_W_V1_1_L2_MAC_BYTES]) {
  UINT32 i;

  if (er_pi_zero_w_v1_1_node_id_nonzero(node_id) == 0u || out_mac == 0) {
    return 0u;
  }
  out_mac[0] = ER_PI_ZERO_W_V1_1_L2_MAC_LOCAL_UNICAST;
  for (i = 0u; i < ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT; ++i) {
    out_mac[ER_PI_ZERO_W_V1_1_L2_MAC_NODE_OFFSET + i] =
        (UINT8)(node_id[i] ^
                node_id[i + ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT] ^
                node_id[i + (ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT * 2u)] ^
                node_id[i + (ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT * 3u)] ^
                node_id[i + (ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT * 4u)] ^
                node_id[i + (ER_PI_ZERO_W_V1_1_L2_MAC_NODE_BYTE_COUNT * 5u)] ^
                node_id[ER_PI_ZERO_W_V1_1_L2_NODE_BYTES - 1u - i]);
  }
  out_mac[0] &= (UINT8)~1u;
  out_mac[0] |= ER_PI_ZERO_W_V1_1_L2_MAC_LOCAL_UNICAST;
  return 1u;
}

static inline UINT8 er_pi_zero_w_v1_1_l2_node_ssid(
    const UINT8 node_id[ER_PI_ZERO_W_V1_1_L2_NODE_BYTES],
    UINT8 out_ssid[ER_PI_ZERO_W_V1_1_L2_SSID_BYTES]) {
  UINT32 i;
  UINT32 ssid_index;
  UINT8 node_byte;

  if (er_pi_zero_w_v1_1_node_id_nonzero(node_id) == 0u || out_ssid == 0) {
    return 0u;
  }
  out_ssid[ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_E_OFFSET] = (UINT8)'e';
  out_ssid[ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_R_OFFSET] = (UINT8)'r';
  out_ssid[ER_PI_ZERO_W_V1_1_L2_SSID_PREFIX_DASH_OFFSET] = (UINT8)'-';
  for (i = 0u; i < ER_PI_ZERO_W_V1_1_L2_SSID_NODE_BYTES; ++i) {
    node_byte = node_id[i];
    ssid_index = ER_PI_ZERO_W_V1_1_L2_SSID_HEX_OFFSET +
                 (i * ER_PI_ZERO_W_V1_1_L2_HEX_DIGITS_PER_BYTE);
    out_ssid[ssid_index] =
        er_pi_zero_w_v1_1_l2_hex_digit(
            (UINT8)(node_byte >> ER_PI_ZERO_W_V1_1_L2_HEX_HIGH_NIBBLE_SHIFT));
    out_ssid[ssid_index + 1u] = er_pi_zero_w_v1_1_l2_hex_digit(node_byte);
  }
  return 1u;
}

static inline UINT8 er_pi_zero_w_v1_1_l2_address(
    const UINT8 node_id[ER_PI_ZERO_W_V1_1_L2_NODE_BYTES],
    UINT8 channel,
    UINT8 out_address[ER_PI_ZERO_W_V1_1_L2_ADDRESS_BYTES]) {
  if (out_address == 0 ||
      er_pi_zero_w_v1_1_l2_node_mac(
          node_id,
          out_address + ER_PI_ZERO_W_V1_1_L2_ADDRESS_MAC_OFFSET) == 0u ||
      er_pi_zero_w_v1_1_l2_node_ssid(
          node_id,
          out_address + ER_PI_ZERO_W_V1_1_L2_ADDRESS_SSID_OFFSET) == 0u) {
    return 0u;
  }
  out_address[ER_PI_ZERO_W_V1_1_L2_ADDRESS_ETH_TYPE_OFFSET] =
      (UINT8)((ER_PI_ZERO_W_V1_1_L2_ETH_TYPE_EDGERUN >>
               ER_PI_ZERO_W_V1_1_L2_ETH_TYPE_HIGH_SHIFT) &
              ER_PI_ZERO_W_V1_1_L2_BYTE_MASK);
  out_address[ER_PI_ZERO_W_V1_1_L2_ADDRESS_ETH_TYPE_OFFSET + 1u] =
      (UINT8)(ER_PI_ZERO_W_V1_1_L2_ETH_TYPE_EDGERUN &
              ER_PI_ZERO_W_V1_1_L2_BYTE_MASK);
  out_address[ER_PI_ZERO_W_V1_1_L2_ADDRESS_CHANNEL_OFFSET] = channel;
  out_address[ER_PI_ZERO_W_V1_1_L2_ADDRESS_SSID_LEN_OFFSET] =
      ER_PI_ZERO_W_V1_1_L2_SSID_BYTES;
  return 1u;
}

static inline UINT32 er_pi_zero_w_v1_1_gpio_fsel_shift(UINT32 pin) {
  return (pin % ER_PI_ZERO_W_V1_1_GPIO_FSEL_PIN_MOD) * ER_PI_ZERO_W_V1_1_GPIO_FSEL_BITS_PER_PIN;
}

static inline UINT32 er_pi_zero_w_v1_1_gpio_fsel_alt(UINT32 current,
                                         UINT32 pin,
                                         UINT32 alt_function) {
  UINT32 shift = er_pi_zero_w_v1_1_gpio_fsel_shift(pin);
  UINT32 mask = ER_PI_ZERO_W_V1_1_GPIO_FSEL_MASK << shift;

  return (current & ~mask) |
         ((alt_function & ER_PI_ZERO_W_V1_1_GPIO_FSEL_MASK) << shift);
}

static inline char er_pi_zero_w_v1_1_serial_hex_digit(UINT32 value) {
  UINT32 digit = value & ER_PI_ZERO_W_V1_1_SERIAL_HEX_NIBBLE_MASK;

  if (digit < ER_PI_ZERO_W_V1_1_SERIAL_HEX_DECIMAL_DIGITS) {
    return (char)('0' + digit);
  }
  return (char)('a' + (digit - ER_PI_ZERO_W_V1_1_SERIAL_HEX_DECIMAL_DIGITS));
}

#endif
