#ifndef ER_WASM_CONTRACT_H
#define ER_WASM_CONTRACT_H

/*
 * Purpose: define the canonical EdgeRun Wasm app contract constants.
 * Intention: keep the compiler and metal runtime on one ABI table.
 */

#define ER_WASM_IMPORT_MODULE_LOG "edgerun.log"
#define ER_WASM_IMPORT_MODULE_PCI "edgerun.pci"
#define ER_WASM_IMPORT_MODULE_MMIO "edgerun.mmio"
#define ER_WASM_IMPORT_MODULE_BUS "edgerun.bus"
#define ER_WASM_IMPORT_MODULE_RELAY "edgerun.relay"
#define ER_WASM_IMPORT_MODULE_MEMORY "edgerun.memory"
#define ER_WASM_IMPORT_MODULE_UI "edgerun.ui"
#define ER_WASM_IMPORT_FIELD_U64 "u64"
#define ER_WASM_IMPORT_FIELD_HEX "hex"
#define ER_WASM_IMPORT_FIELD_READ32 "read32"
#define ER_WASM_IMPORT_FIELD_WRITE32 "write32"
#define ER_WASM_IMPORT_FIELD_MAP "map"
#define ER_WASM_IMPORT_FIELD_EXEC "exec"
#define ER_WASM_IMPORT_FIELD_SEND "send"
#define ER_WASM_IMPORT_FIELD_RECV "recv"
#define ER_WASM_IMPORT_FIELD_EMIT "emit"
#define ER_WASM_IMPORT_FIELD_REGION_BASE "region_base"
#define ER_WASM_IMPORT_FIELD_REGION_LEN "region_len"

#define ER_WASM_CONTRACT_REQUIRED_MEMORY_PAGES 1u
#define ER_WASM_CONTRACT_REQUIRED_IMPORT_COUNT 1u
#define ER_WASM_HOSTCALL_NO_PARAMS 0u
#define ER_WASM_HOSTCALL_UNARY_PARAMS 1u
#define ER_WASM_HOSTCALL_BINARY_PARAMS 2u
#define ER_WASM_HOSTCALL_NO_RESULTS 0u
#define ER_WASM_HOSTCALL_I64_RESULTS 1u
#define ER_WASM_PCI_READ32_PARAM_COUNT 4u
#define ER_WASM_PCI_WRITE32_PARAM_COUNT 5u
#define ER_WASM_CONTRACT_MASK_NONE 0u
#define ER_WASM_CONTRACT_MASK_UI_APP 1u
#define ER_WASM_CONTRACT_MASK_BUS_DRIVER 2u

typedef enum {
  ER_WASM_MODULE_CONTRACT_NONE = 0,
  ER_WASM_MODULE_CONTRACT_UI_APP = 1,
  ER_WASM_MODULE_CONTRACT_BUS_DRIVER = 2
} ErWasmModuleContract;

typedef enum {
  ER_WASM_IMPORT_KIND_NONE = 0,
  ER_WASM_IMPORT_KIND_LOG_U64 = 1,
  ER_WASM_IMPORT_KIND_LOG_HEX = 2,
  ER_WASM_IMPORT_KIND_PCI_READ32 = 3,
  ER_WASM_IMPORT_KIND_PCI_WRITE32 = 4,
  ER_WASM_IMPORT_KIND_MMIO_MAP = 5,
  ER_WASM_IMPORT_KIND_MMIO_READ32 = 6,
  ER_WASM_IMPORT_KIND_BUS_EXEC = 7,
  ER_WASM_IMPORT_KIND_RELAY_SEND = 8,
  ER_WASM_IMPORT_KIND_RELAY_RECV = 9,
  ER_WASM_IMPORT_KIND_MEMORY_REGION_BASE = 10,
  ER_WASM_IMPORT_KIND_MEMORY_REGION_LEN = 11,
  ER_WASM_IMPORT_KIND_UI_EMIT = 12
} ErWasmImportKind;

#define ER_WASM_CONTRACT_IMPORTS(X) \
  X(ER_WASM_IMPORT_KIND_LOG_U64, ER_WASM_IMPORT_MODULE_LOG, ER_WASM_IMPORT_FIELD_U64, \
    ER_WASM_HOSTCALL_UNARY_PARAMS, ER_WASM_HOSTCALL_NO_RESULTS, \
    ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_LOG_HEX, ER_WASM_IMPORT_MODULE_LOG, ER_WASM_IMPORT_FIELD_HEX, \
    ER_WASM_HOSTCALL_UNARY_PARAMS, ER_WASM_HOSTCALL_NO_RESULTS, \
    ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_PCI_READ32, ER_WASM_IMPORT_MODULE_PCI, \
    ER_WASM_IMPORT_FIELD_READ32, ER_WASM_PCI_READ32_PARAM_COUNT, \
    ER_WASM_HOSTCALL_I64_RESULTS, ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_PCI_WRITE32, ER_WASM_IMPORT_MODULE_PCI, \
    ER_WASM_IMPORT_FIELD_WRITE32, ER_WASM_PCI_WRITE32_PARAM_COUNT, \
    ER_WASM_HOSTCALL_NO_RESULTS, ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_MMIO_MAP, ER_WASM_IMPORT_MODULE_MMIO, ER_WASM_IMPORT_FIELD_MAP, \
    ER_WASM_HOSTCALL_BINARY_PARAMS, ER_WASM_HOSTCALL_I64_RESULTS, \
    ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_MMIO_READ32, ER_WASM_IMPORT_MODULE_MMIO, \
    ER_WASM_IMPORT_FIELD_READ32, ER_WASM_HOSTCALL_BINARY_PARAMS, \
    ER_WASM_HOSTCALL_I64_RESULTS, ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_BUS_EXEC, ER_WASM_IMPORT_MODULE_BUS, ER_WASM_IMPORT_FIELD_EXEC, \
    ER_WASM_HOSTCALL_BINARY_PARAMS, ER_WASM_HOSTCALL_I64_RESULTS, \
    ER_WASM_CONTRACT_MASK_BUS_DRIVER) \
  X(ER_WASM_IMPORT_KIND_RELAY_SEND, ER_WASM_IMPORT_MODULE_RELAY, ER_WASM_IMPORT_FIELD_SEND, \
    ER_WASM_HOSTCALL_BINARY_PARAMS, ER_WASM_HOSTCALL_I64_RESULTS, \
    ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_RELAY_RECV, ER_WASM_IMPORT_MODULE_RELAY, ER_WASM_IMPORT_FIELD_RECV, \
    ER_WASM_HOSTCALL_BINARY_PARAMS, ER_WASM_HOSTCALL_I64_RESULTS, \
    ER_WASM_CONTRACT_MASK_NONE) \
  X(ER_WASM_IMPORT_KIND_MEMORY_REGION_BASE, ER_WASM_IMPORT_MODULE_MEMORY, \
    ER_WASM_IMPORT_FIELD_REGION_BASE, ER_WASM_HOSTCALL_UNARY_PARAMS, \
    ER_WASM_HOSTCALL_I64_RESULTS, ER_WASM_CONTRACT_MASK_UI_APP) \
  X(ER_WASM_IMPORT_KIND_MEMORY_REGION_LEN, ER_WASM_IMPORT_MODULE_MEMORY, \
    ER_WASM_IMPORT_FIELD_REGION_LEN, ER_WASM_HOSTCALL_UNARY_PARAMS, \
    ER_WASM_HOSTCALL_I64_RESULTS, ER_WASM_CONTRACT_MASK_UI_APP) \
  X(ER_WASM_IMPORT_KIND_UI_EMIT, ER_WASM_IMPORT_MODULE_UI, ER_WASM_IMPORT_FIELD_EMIT, \
    ER_WASM_HOSTCALL_BINARY_PARAMS, ER_WASM_HOSTCALL_I64_RESULTS, \
    ER_WASM_CONTRACT_MASK_UI_APP)

#endif
